# Generated by Django 2.0.3 on 2020-01-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_report',
            name='ctime',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='test_report',
            name='test_time',
            field=models.IntegerField(max_length=10),
        ),
    ]
